# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Menu
from chrono_button import ChronoButton

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\naths\source\repos\infinite-chrono\gui\assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.title("Infinite Chrono")
window.geometry("1280x720")
window.configure(bg = "#FFFFFF")

def generate_gui():
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 720,
        width = 1280,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        203.0,
        720.0,
        fill="#FFE8E8",
        outline="")

    canvas.create_text(
        279.0,
        347.0,
        anchor="nw",
        text="History",
        fill="#000000",
        font=("ArialMT", 24 * -1)
    )

    canvas.create_rectangle(
        374.0,
        358.9999999421614,
        1280.0,
        360.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        202.0,
        359.0,
        281.0,
        360.0,
        fill="#000000",
        outline="")

    canvas.create_text(
        57.0,
        14.0,
        anchor="nw",
        text="Chronos",
        fill="#000000",
        font=("ArialMT", 24 * -1)
    )

    canvas.create_rectangle(
        -0.9987678527832031,
        95.5,
        203.00368881225586,
        96.5,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        201.03598022460938,
        -0.998509407043457,
        202.0359802246095,
        720.004298210144,
        fill="#000000",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        41.0,
        46.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:ChronoButton(window),
        relief="flat"
    )
    button_1.place(
        x=12.0,
        y=113.0,
        width=182.0,
        height=69.0
    )

    window.resizable(True, True)
    window.mainloop()
